site_name: Python Brevísimo

nav:
  - Principal: index.md
  - Introducción: intro.md
  - Datos: datos.md
  - Variables: variables.md
  - Bucles: bucles.md
  - Bucle for: bucles/for.md
  - Listas: listas.md
  - Funciones: funciones.md


theme:
  name: material
  palette: 
    scheme: default
    primary: amber
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tracking
    - content.tooltips

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - attr_list

extra_css:
  - css/extra.css
