site_name: Python Brevísimo
theme:
  name: material
  palette: 
    scheme: default
    primary: amber
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tracking

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - css/extra.css
