site_name: Python Brevísimo

nav:
  - Principal: index.md
  - Introducción: intro.md
  - Datos: datos.md
  - Variables: variables.md
  - Alternativa if: if.md
  - Bucles: bucles.md
  - Bucle for: bucles/for.md
  - Bucle while: bucles/while.md
  - Listas: listas.md
  - Cadenas: cadenas.md
  - Funciones: funciones.md
  - Funciones básicas: funciones/func_base.md
  - Funciones avanzadas: funciones/func_av.md
  - Objetos: objetos.md
  - GUI: gui.md
  - PySide6: pyside6.md

theme:
  language: es
  font:
    text: Noto Sans
    code: JetBrains Mono
    
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Cambiar a modo oscuro

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tooltips
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.tilde
  - md_in_html
      
  
extra_css:
  - css/extra.css
