site_name: Python Brevísimo

nav:
  - Principal: index.md
  - Introducción: intro.md
  - Datos: datos.md
  - Variables: variables.md
  - Operaciones: operaciones.md
  - Alternativa: if.md
  - Bucles: 
    - bucles/index.md
    - Bucle for: bucles/for.md
    - Bucle while: bucles/while.md
  
theme:
  language: es
  font:
    text: Noto Sans
    code: JetBrains Mono
    
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Cambiar a modo oscuro

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.tilde
  - md_in_html
      
  
extra_css:
  - css/extra.css
