site_name: Python Brevísimo

nav:
  - Principal: index.md
  - Intro: intro.md
  - Datos: datos.md
  - Bucles:
    - for: bucles/for.md
    - while: bucles/while.md

theme:
  name: material
  palette: 
    scheme: default
    primary: amber
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tracking
    - content.tooltips

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - attr_list

extra_css:
  - css/extra.css
